# Netlify configuration for tik-in-de-buurt project
[build]
  command = "node -v && npm ci && npm run build"
  publish = "dist"

[build.environment]
  # Force Node 20.x for compatibility
  NODE_VERSION = "20"
  # Frontend environment variables for Netlify deployment
  VITE_API_URL = "https://your-backend-domain.com/api"
  VITE_USE_MOCK_API = "false"

# SPA routing - redirect all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy redirects (if using Netlify Functions)
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-domain.com/api/:splat"
  status = 200
  force = true

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' https:; connect-src 'self' https:;"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache JavaScript and CSS
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment-specific settings for different branches
[context.production.environment]
  VITE_API_URL = "https://your-production-backend.com/api"
  VITE_USE_MOCK_API = "false"

[context.deploy-preview.environment]
  VITE_API_URL = "https://your-staging-backend.com/api"
  VITE_USE_MOCK_API = "true"

[context.branch-deploy.environment]
  VITE_API_URL = "http://localhost:8080/api"
  VITE_USE_MOCK_API = "true"

# Dev settings
[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"