
import type { Language, Business, Ad, Category, Review, Comment, LiveChatMessage, PropertyListing, JobCategory, Freelancer, Post, Plan, Invoice, AdAnalyticsData, CV } from './types';
import { NlFlag, EnFlag, TrFlag, PlFlag, BgFlag, ArFlag, DeFlag, HuFlag, FrFlag } from '../components/icons/Flags';
import { PropertyStatus, PropertyType, PostType } from './types';

export const LANGUAGES: Language[] = [
  { code: 'nl', name: 'Nederlands', flag: NlFlag },
  { code: 'en', name: 'English', flag: EnFlag },
  { code: 'tr', name: 'Türkçe', flag: TrFlag },
  { code: 'pl', name: 'Polski', flag: PlFlag },
  { code: 'bg', name: 'Български', flag: BgFlag },
  { code: 'ar', name: 'العربية', flag: ArFlag },
  { code: 'de', name: 'Deutsch', flag: DeFlag },
  { code: 'hu', name: 'Magyar', flag: HuFlag },
  { code: 'fr', name: 'Français', flag: FrFlag },
];

export const CITIES: string[] = ['Den Haag', 'Rotterdam', 'Amsterdam', 'Moerdijk'];

// API Configuration
export const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:3001';
export const CATEGORIES: Category[] = [
  'category_horeca', 
  'category_retail', 
  'category_beauty_wellness',
  'category_health_medical',
  'category_construction_trades',
  'category_automotive',
  'category_legal_financial',
  'category_education',
  'category_events_entertainment',
  'category_home_garden',
  'category_pets',
  'category_sports_fitness',
  'category_professional_services',
  'category_real_estate',
  'category_travel_tourism',
  'category_it_technology',
  'category_creative_arts',
  'category_childcare',
  'category_non_profit',
  'category_transport_logistics',
  'category_fashion',
  'category_food_drink',
  'category_doctors',
  'category_dentists',
  'category_physiotherapists',
  'category_hairdressers',
  'category_beauticians',
  'category_personal_trainers',
  'category_builders',
  'category_plumbers',
  'category_electricians',
  'category_painters',
  'category_carpenters',
  'category_chefs',
  'category_bakers',
  'category_butchers',
  'category_accountants',
  'category_lawyers',
  'category_consultants',
  'category_cleaning_services',
  'category_real_estate_agents',
  'category_photographers',
  'category_designers',
  'category_mechanics',
  'category_gardening_services',
  'category_childminders',
  'category_architects',
  'category_catering',
  'category_coaching',
  'category_bicycle_shops',
  'category_tutoring',
  'category_interior_design',
  'category_handyman_services',
  'category_marketing_agencies',
  'category_notaries',
  'category_driving_schools',
  'category_tattoo_artists',
  'category_taxi_services',
  'category_translators',
  'category_moving_services',
  'category_web_design',
  'category_yoga_pilates',
  'category_freelance_healthcare',
  'category_galleries',
  'category_theaters',
  'category_dance_studios',
  'category_hr_consultants',
  'category_it_support',
  'category_insurance_agents',
  'category_car_washes',
  'category_car_rental',
  'category_pharmacies',
  'category_chiropractors',
  'category_home_care',
  'category_pool_maintenance',
  'category_pest_control',
  'category_roofers',
  'category_wineries',
  'category_breweries',
  'category_delicatessens',
  'category_pet_grooming',
  'category_storage_facilities',
  'category_florists'
];

export const JOB_CATEGORIES: JobCategory[] = [
    { id: 'painting', translationKey: 'job_category_painting' },
    { id: 'tiling', translationKey: 'job_category_tiling' },
    { id: 'plumbing', translationKey: 'job_category_plumbing' },
    { id: 'electrical', translationKey: 'job_category_electrical' },
    { id: 'gardening', translationKey: 'job_category_gardening' },
    { id: 'carpentry', translationKey: 'job_category_carpentry' },
    { id: 'plastering', translationKey: 'job_category_plastering' },
    { id: 'flooring', translationKey: 'job_category_flooring' },
    { id: 'demolition', translationKey: 'job_category_demolition' },
    { id: 'insulation', translationKey: 'job_category_insulation' },
];

export const MOCK_PLANS: Plan[] = [
    {
        id: 'plan_monthly',
        nameKey: 'plan_monthly_title',
        price: 15.99,
        intervalKey: 'month',
        features: ['feature_unlimited_ads', 'feature_video_support']
    },
    {
        id: 'plan_yearly',
        nameKey: 'plan_yearly_title',
        price: 149.99,
        originalPrice: 191.88,
        intervalKey: 'year',
        priceNoteKey: 'plan_yearly_promo_subtitle',
        isPopular: true,
        features: ['feature_unlimited_ads', 'feature_video_support', 'feature_top_placement', 'feature_verified_badge']
    },
    {
        id: 'plan_two_year',
        nameKey: 'plan_two_year_title',
        price: 249.99,
        intervalKey: '2_years',
        features: ['feature_unlimited_ads', 'feature_video_support', 'feature_top_placement', 'feature_verified_badge', 'feature_premium_support']
    }
];

const MOCK_CV_BUSINESS_1: CV = {
    summary: 'A creative and business-savvy fashion entrepreneur with over a decade of experience in retail management and brand development. Proven ability to grow revenue and enhance brand visibility in competitive markets.',
    experience: [
        { job_title: 'Owner & Creative Director', company: 'Fashion Store', start_date: '2015-01', end_date: '', is_current: true, location: 'Rotterdam, NL', employment_type: 'full-time', description: 'Founded and managed a boutique fashion store, overseeing all aspects from product curation and marketing to sales and customer relations.', achievements: [], tech_stack: [], links: [] }
    ],
    education: [{ degree: 'Bachelor of Fashion Business', institution: 'Amsterdam Fashion Academy', start_date: '2006-09', end_date: '2009-06' }],
    projects: [],
    skills: ['Fashion Design', 'Retail Management', 'Merchandising', 'Brand Strategy', 'E-commerce'],
    languages: [{ language: 'Dutch', proficiency: 'Native' }, { language: 'English', proficiency: 'Advanced' }],
    certifications: [
        { name: 'Fashion Business Management', issuer: 'Amsterdam Fashion Academy', date: '2010-01' }
    ],
};

export const MOCK_BUSINESSES: Business[] = [
  {
    id: 1,
    ownerId: 1,
    nameKey: "mock_business_name_1",
    descriptionKey: "mock_business_description_4", // Using a generic one for now
    categoryKey: "category_fashion",
    logoUrl: "https://i.imgur.com/8p8YJH8.png",
    coverImageUrl: "https://i.imgur.com/9E6qB8E.jpeg",
    rating: 4.5,
    adCount: 8,
    reviewCount: 17,
    isVerified: true,
    phone: "+31101234567",
    website: "https://fashionstore.nl",
    googleMapsUrl: "https://maps.google.com/?cid=12345",
    instagram: "fashionstore",
    facebook: "https://facebook.com/fashionstore",
    twitter: "https://twitter.com/fashionstore",
    linkedin: "https://linkedin.com/company/fashionstore",
    tiktokUrl: "https://tiktok.com/@fashionstore",
    openingHours: { "Ma-Za": "10:00 - 18:00", "Zo": "Gesloten" },
    services: [{name: "Personal Styling"}, {name: "Click & Collect"}, {name: "Tailoring"}],
    address: { street: "Lijnbaan 10", postalCode: "3012 EK", city: "Rotterdam", country: "Netherlands" },
    kvkNumber: "12345678",
    btwNumber: "NL123456789B01",
    iban: "NL91ABNA0417164300",
    establishedYear: 2015,
    teamSize: "6-20",
    paymentMethods: ["PIN", "Credit Card", "Contant"],
    spokenLanguages: ["Nederlands", "Engels"],
    companyMotto: "Dress with passion.",
    sustainabilityInfo: "We use 100% organic cotton and recycled materials in our new collection.",
    certifications: ["Fair Wear Foundation", "GOTS Certified"],
    otherLocations: [
      { street: "Kalverstraat 5", postalCode: "1012 NX", city: "Amsterdam", country: "Netherlands" }
    ],
    createdAt: "2023-01-15T10:00:00Z",
    subscriptionStatus: "active",
    subscriptionExpiresAt: "2025-06-15T10:00:00Z",
    planId: "plan_yearly",
    cv: MOCK_CV_BUSINESS_1,
  },
  {
    id: 2,
    ownerId: 2,
    nameKey: "mock_business_name_2",
    descriptionKey: "mock_business_description_2",
    categoryKey: "category_food_drink",
    logoUrl: "https://i.imgur.com/sC3bL2T.png",
    coverImageUrl: "https://i.imgur.com/O2jOC2c.jpeg",
    rating: 4.9,
    adCount: 3,
    reviewCount: 42,
    isVerified: false,
    phone: "+31708901234",
    website: "https://coffeecorner.nl",
    googleMapsUrl: "https://maps.google.com/?cid=67890",
    instagram: "coffeecorner",
    facebook: "https://facebook.com/coffeecorner",
    twitter: "https://twitter.com/coffeecorner",
    linkedin: "https://linkedin.com/company/coffeecorner",
    openingHours: { "Ma-Vr": "07:00 - 18:00", "Za-Zo": "09:00 - 19:00" },
    services: [{name: "Specialty Coffee"}, {name: "Fresh Pastries"}, {name: "WiFi Workspace"}],
    address: { street: "Noordeinde 50", postalCode: "2514 GK", city: "Den Haag", country: "Netherlands" },
    kvkNumber: "87654321",
    btwNumber: "NL987654321B01",
    iban: "NL26INGB0001234567",
    establishedYear: 2018,
    teamSize: "1-5",
    paymentMethods: ["PIN", "Tikkie", "Contant"],
    spokenLanguages: ["Nederlands", "Engels"],
    createdAt: "2023-03-20T12:00:00Z",
    subscriptionStatus: "active",
    subscriptionExpiresAt: "2025-02-28T12:00:00Z",
    planId: 'plan_monthly',
  },
  {
    id: 3,
    ownerId: 3,
    nameKey: "mock_business_name_3",
    descriptionKey: "mock_business_description_3",
    categoryKey: "category_horeca",
    logoUrl: "https://i.imgur.com/Yq2f0bJ.png",
    coverImageUrl: "https://i.imgur.com/Uu8S02j.jpeg",
    rating: 4.8,
    adCount: 5,
    reviewCount: 25,
    isVerified: false,
    phone: "+31205678901",
    website: "https://mariospizza.nl",
    instagram: "mariospizza",
    facebook: "https://facebook.com/mariospizza",
    twitter: "https://twitter.com/mariospizza",
    linkedin: "https://linkedin.com/company/mariospizza",
    openingHours: { "Di-Zo": "17:00 - 22:00", "Ma": "Gesloten" },
    services: [{name: "Wood-fired Pizza"}, {name: "Home Delivery"}, {name: "Vegan Options"}],
    address: { street: "Leidsestraat 99", postalCode: "1017 NZ", city: "Amsterdam", country: "Netherlands" },
    kvkNumber: "11223344",
    btwNumber: "NL112233445B01",
    iban: "NL55RABO0987654321",
    createdAt: "2022-11-01T18:00:00Z",
    subscriptionStatus: "inactive",
  },
  {
    id: 4,
    ownerId: 4,
    nameKey: "mock_business_name_4",
    descriptionKey: "mock_business_description_4",
    categoryKey: "category_home_garden",
    logoUrl: "https://i.imgur.com/3flwzJm.png",
    coverImageUrl: "https://i.imgur.com/zW1r5pX.jpeg",
    rating: 4.7,
    adCount: 2,
    reviewCount: 8,
    isVerified: false,
    phone: "+31702345678",
    website: "https://bloemenparadise.nl",
    instagram: "bloemenparadise",
    facebook: "https://facebook.com/bloemenparadise",
    twitter: "https://twitter.com/bloemenparadise",
    linkedin: "https://linkedin.com/company/bloemenparadise",
    openingHours: { "Ma-Za": "09:00 - 17:00", "Zo": "12:00 - 17:00" },
    services: [{name: "Bouquets"}, {name: "Wedding Arrangements"}, {name: "Plants"}],
    address: { street: "Frederik Hendriklaan 200", postalCode: "2582 BK", city: "Den Haag", country: "Netherlands" },
    kvkNumber: "55667788",
    btwNumber: "NL556677889B01",
    iban: "NL30ASNB0123456789",
    createdAt: "2024-02-10T09:00:00Z",
    subscriptionStatus: "expired",
    subscriptionExpiresAt: "2024-05-01T09:00:00Z",
  },
   {
    id: 5,
    ownerId: 5,
    nameKey: "Den Haag Makelaars",
    descriptionKey: "Your expert partner in finding the perfect home in The Hague area. We offer personalized service and local expertise.",
    categoryKey: "category_real_estate_agents",
    logoUrl: "https://i.imgur.com/g8e1cDm.png",
    coverImageUrl: "https://i.imgur.com/Y3zJ9bY.jpeg",
    rating: 4.9,
    adCount: 4,
    reviewCount: 38,
    isVerified: true,
    phone: "+31705551234",
    website: "https://denhaagmakelaars.nl",
    googleMapsUrl: "https://maps.google.com/?cid=98765",
    instagram: "denhaagmakelaars",
    facebook: "https://facebook.com/denhaagmakelaars",
    twitter: "https://twitter.com/denhaagmakelaars",
    linkedin: "https://linkedin.com/company/denhaagmakelaars",
    openingHours: { "Ma-Vr": "09:00 - 17:30", "Za": "Op afspraak", "Zo": "Gesloten" },
    services: [{name: "Aankoopbegeleiding"}, {name: "Verkoopbegeleiding"}, {name: "Taxaties"}, {name: "Huuradvies"}],
    address: { street: "Lange Voorhout 15", postalCode: "2514 EA", city: "Den Haag", country: "Netherlands" },
    kvkNumber: "27384950",
    btwNumber: "NL273849501B01",
    iban: "NL88RABO0123456789",
    createdAt: "2021-08-01T09:00:00Z",
    subscriptionStatus: "active",
    subscriptionExpiresAt: "2025-08-01T09:00:00Z",
    planId: "plan_yearly"
  },
  {
    id: 6,
    ownerId: 6,
    nameKey: "TechFix Electronics",
    descriptionKey: "Fast and reliable repairs for all your electronic devices. Laptops, phones, and more.",
    categoryKey: "category_it_technology",
    logoUrl: "https://i.imgur.com/jXqQp6j.jpeg",
    coverImageUrl: "https://i.imgur.com/lQW9A8d.jpeg",
    rating: 4.6,
    adCount: 1,
    reviewCount: 31,
    isVerified: false,
    phone: "+31209876543",
    website: "https://techfix.nl",
    instagram: "techfixnl",
    facebook: "https://facebook.com/techfixnl",
    twitter: "https://twitter.com/techfixnl",
    linkedin: "https://linkedin.com/company/techfixnl",
    openingHours: { "Ma-Za": "10:00 - 19:00", "Zo": "Gesloten" },
    services: [{name: "Phone Repair"}, {name: "Laptop Repair"}, {name: "Data Recovery"}],
    address: { street: "Kinkerstraat 50", postalCode: "1053 DV", city: "Amsterdam", country: "Netherlands" },
    kvkNumber: "99887766",
    btwNumber: "NL998877665B01",
    iban: "NL12INGB0987654321",
    createdAt: "2023-09-01T11:00:00Z",
    subscriptionStatus: "past_due",
    subscriptionExpiresAt: "2024-07-01T11:00:00Z",
    planId: "plan_yearly",
  }
];

export const MOCK_INVOICES: Invoice[] = [
    { id: 'inv_123', businessId: 1, date: '2024-06-15', amount: 95.99, status: 'paid', pdfUrl: '#' },
    { id: 'inv_122', businessId: 1, date: '2023-06-15', amount: 95.99, status: 'paid', pdfUrl: '#' },
    { id: 'inv_A56', businessId: 2, date: '2024-06-28', amount: 15.99, status: 'paid', pdfUrl: '#' },
    { id: 'inv_A55', businessId: 2, date: '2024-05-28', amount: 15.99, status: 'paid', pdfUrl: '#' },
    { id: 'inv_B78', businessId: 6, date: '2024-07-01', amount: 95.99, status: 'failed', pdfUrl: '#' },
    { id: 'inv_B77', businessId: 6, date: '2023-07-01', amount: 95.99, status: 'paid', pdfUrl: '#' },
];

export const MOCK_AD_ANALYTICS: AdAnalyticsData[] = [
    {
        adId: 1,
        impressions: 25830,
        ctr: 4.86,
        engagementRate: 12.3,
        trend: [
            { date: 'Day 1', views: 500 }, { date: 'Day 2', views: 800 }, { date: 'Day 3', views: 1200 },
            { date: 'Day 4', views: 1100 }, { date: 'Day 5', views: 1500 }, { date: 'Day 6', views: 1800 },
            { date: 'Day 7', views: 2100 }
        ]
    },
    {
        adId: 2,
        impressions: 15210,
        ctr: 5.87,
        engagementRate: 9.1,
        trend: [
            { date: 'Day 1', views: 300 }, { date: 'Day 2', views: 450 }, { date: 'Day 3', views: 600 },
            { date: 'Day 4', views: 700 }, { date: 'Day 5', views: 900 }, { date: 'Day 6', views: 850 },
            { date: 'Day 7', views: 1100 }
        ]
    }
];

const MOCK_CV_1: CV = {
    summary: 'Experienced painter with a keen eye for detail. I provide a sleek and durable finish, for both interior and exterior projects, ensuring high-quality results that last.',
    experience: [
        {
            job_title: 'Lead Painter',
            company: 'Schildersbedrijf de Vries',
            start_date: '2020-01',
            end_date: '',
            is_current: true,
            location: 'Den Haag, NL',
            employment_type: 'full-time',
            description: 'Managed a team of painters for residential and commercial projects, ensuring projects were completed on time and to the highest standards.',
            achievements: ['Increased client satisfaction by 25% through meticulous prep work.', 'Reduced project completion time by 15% by optimizing team workflows.'],
            tech_stack: ['Farrow & Ball', 'Sikkens', 'Airless Spraying'],
            links: [],
        },
        {
            job_title: 'Painting Apprentice',
            company: 'Kleur & Co.',
            start_date: '2018-06',
            end_date: '2019-12',
            is_current: false,
            location: 'Rotterdam, NL',
            employment_type: 'internship',
            description: 'Assisted senior painters in all aspects of interior and exterior painting, including surface preparation, paint mixing, and application.',
            achievements: [],
            tech_stack: [],
            links: [],
        }
    ],
    education: [{ degree: 'Painting & Decorating Vocational Certificate', institution: 'ROC Mondriaan', start_date: '2018-09', end_date: '2020-06' }],
    projects: [{ name: 'Mauritshuis Renovation', description: 'Participated in the decorative finishing of several exhibition rooms during the 2022 renovation.' }],
    skills: ['Interior Painting', 'Exterior Painting', 'Wallpapering', 'Color Theory', 'Surface Preparation', 'Woodwork Finishing'],
    languages: [{ language: 'Dutch', proficiency: 'Native' }, { language: 'English', proficiency: 'Intermediate' }],
    certifications: [
        { name: 'VCA Certificate', issuer: 'SGS', date: '2021-03' }
    ],
};

const MOCK_CV_2: CV = {
    summary: 'Detail-oriented tiler specializing in high-end bathroom and kitchen renovations. I work with all types of tiles, from ceramic to natural stone, delivering flawless and waterproof installations.',
    experience: [
        {
            job_title: 'Freelance Tiler',
            company: 'Self-Employed',
            start_date: '2018-03',
            end_date: '',
            is_current: true,
            location: 'Rotterdam, NL',
            employment_type: 'contract',
            description: 'Successfully completed numerous tiling projects for private clients, focusing on bathroom floors, kitchen backsplashes, and custom mosaic designs.',
            achievements: ['Completed over 50 bathroom renovations with a 100% success rate.', 'Received consistent 5-star ratings for craftsmanship and professionalism.'],
            tech_stack: ['Ceramic', 'Porcelain', 'Natural Stone', 'Schluter Systems', 'Wet Saw Operation'],
            links: [],
        }
    ],
    education: [{ degree: 'Certified Tiler', institution: 'Tiling Technical College', start_date: '2016-09', end_date: '2018-06' }],
    projects: [],
    skills: ['Tiling', 'Grouting', 'Waterproofing', 'Mosaic Tiling', 'Floor Leveling'],
    languages: [{ language: 'Polish', proficiency: 'Native' }, { language: 'Dutch', proficiency: 'Beginner' }],
    certifications: [
        { name: 'Certified Tile Installer', issuer: 'CTE Institute', date: '2019-08' }
    ],
};

const MOCK_CV_3: CV = {
    summary: 'Creative gardener and landscape designer dedicated to transforming outdoor spaces into beautiful and functional gardens. From initial design to ongoing maintenance, I bring your garden dreams to life.',
    experience: [],
    education: [{ degree: 'BSc in Horticulture & Landscape Design', institution: 'Wageningen University', start_date: '2015-09', end_date: '2019-06' }],
    projects: [
        { name: 'Urban Rooftop Garden', description: 'Designed and installed a sustainable rooftop garden for a commercial building in Amsterdam, featuring native plants and an irrigation system.' },
        { name: 'Family Garden Redesign', description: 'Transformed a traditional backyard into a modern, low-maintenance space with distinct zones for relaxation and play.' }
    ],
    skills: ['Garden Design', 'Landscaping', 'Planting & Plant Care', 'Irrigation Systems', 'Pruning', 'Soil Management'],
    languages: [{ language: 'Dutch', proficiency: 'Native' }],
    certifications: [],
};


export const MOCK_FREELANCERS: Freelancer[] = [
    {
        id: 1,
        nameKey: "freelancer_name_1",
        city: "Den Haag",
        rating: 4.9,
        reviewCount: 34,
        specializationKey: "job_category_painting",
        profileImageUrl: "https://i.imgur.com/lQW9A8d.jpeg",
        aboutKey: "freelancer_about_1",
        services: [
            { nameKey: "Binnenschilderwerk", price: "€35/uur" },
            { nameKey: "Buitenschilderwerk", price: "€40/uur" },
            { nameKey: "Behangen", price: "Op aanvraag" },
        ],
        portfolioImages: ["https://i.imgur.com/aP7O3lS.jpeg", "https://i.imgur.com/tZ2M9iA.jpeg", "https://i.imgur.com/3V2v1Xv.jpeg"],
        instagram: "https://instagram.com/janschilder",
        website: "https://janschilder.nl",
        twitter: "https://twitter.com/janschilder",
        cv: MOCK_CV_1,
    },
    {
        id: 2,
        nameKey: "freelancer_name_2",
        city: "Rotterdam",
        rating: 4.8,
        reviewCount: 22,
        specializationKey: "job_category_tiling",
        profileImageUrl: "https://i.imgur.com/sC3bL2T.png",
        aboutKey: "freelancer_about_2",
        services: [
            { nameKey: "Badkamer betegelen", price: "Vanaf €1200" },
            { nameKey: "Keukenvloer leggen", price: "€45/m²" },
        ],
        portfolioImages: ["https://i.imgur.com/uFLmC9u.jpeg", "https://i.imgur.com/pA1jM4r.jpeg"],
        facebook: "https://facebook.com/piotrtegel",
        cv: MOCK_CV_2,
    },
    {
        id: 3,
        nameKey: "freelancer_name_3",
        city: "Amsterdam",
        rating: 5.0,
        reviewCount: 15,
        specializationKey: "job_category_gardening",
        profileImageUrl: "https://i.imgur.com/Yq2f0bJ.png",
        aboutKey: "freelancer_about_3",
        services: [
            { nameKey: "Tuinonderhoud", price: "€50/uur" },
            { nameKey: "Tuinontwerp", price: "Op aanvraag" },
            { nameKey: "Bestrating", price: "Op aanvraag" },
        ],
        portfolioImages: ["https://i.imgur.com/iR3u8tG.jpeg", "https://i.imgur.com/dZ1nQ5d.jpeg"],
        website: "https://hovenierhans.nl",
        cv: MOCK_CV_3,
    }
];

export let MOCK_REVIEWS: Review[] = [
    { id: 7, freelancerId: 1, author: "Anna V.", authorType: 'user', avatarUrl: "https://i.imgur.com/4YwP5E8.jpg", rating: 5, text: "Jan did an amazing job painting our living room. Very professional and clean work. Highly recommended!", date: "2024-06-01" },
    { id: 8, freelancerId: 1, author: "Mark D.", authorType: 'user', avatarUrl: "https://i.imgur.com/O2jOC2c.jpeg", rating: 4, text: "Good work, but was a little late on the last day. Overall satisfied with the result.", date: "2024-05-15" },
    { id: 9, freelancerId: 2, author: "Sophie L.", authorType: 'user', avatarUrl: "https://i.imgur.com/9E6qB8E.jpeg", rating: 5, text: "Piotr is a true craftsman. Our new bathroom floor looks stunning. He is very precise and reliable.", date: "2024-05-20" },
    { id: 10, freelancerId: 3, author: "Ben T.", authorType: 'user', avatarUrl: "https://i.imgur.com/sC3bL2T.png", rating: 5, text: "Hans transformed our messy backyard into a paradise. He listened to all our wishes and delivered beyond expectations.", date: "2024-04-30" },
    { 
      id: 6, 
      businessId: 3, 
      author: "Coffee Corner", 
      authorType: 'business', 
      authorBusinessId: 2, 
      avatarUrl: "https://i.imgur.com/sC3bL2T.png", 
      rating: 5, 
      text: "Mario's pizza is the perfect fuel for our baristas! Always delicious, always on time. A fantastic local partner.", 
      date: "2024-05-21" 
    },
    { id: 1, businessId: 2, authorType: 'user', author: "Anna V.", avatarUrl: "https://i.imgur.com/4YwP5E8.jpg", rating: 5, text: "Absolutely the best coffee in The Hague. The atmosphere is cozy and the staff are super friendly. A must-visit!", date: "2024-05-10" },
    { id: 2, businessId: 2, authorType: 'user', author: "Mark D.", avatarUrl: "https://i.imgur.com/O2jOC2c.jpeg", rating: 4, text: "Great place to work and enjoy a good cup of coffee. Can get a bit busy during peak hours, but worth it.", date: "2024-05-08" },
    { id: 3, businessId: 3, authorType: 'user', author: "Luigi M.", avatarUrl: "https://i.imgur.com/Yq2f0bJ.png", rating: 5, text: "As an Italian, I approve! The pizza is authentic and delicious. Reminds me of home.", date: "2024-05-12" },
    { id: 4, businessId: 1, authorType: 'user', author: "Sophie L.", avatarUrl: "https://i.imgur.com/9E6qB8E.jpeg", rating: 5, text: "Found the perfect dress here. The staff was incredibly helpful with styling advice.", date: "2024-04-28" },
    { id: 5, businessId: 2, authorType: 'user', author: "Ben T.", avatarUrl: "https://i.imgur.com/sC3bL2T.png", rating: 5, text: "Their flat white is a game-changer. Seriously, you have to try it.", date: "2024-04-25" },
];

export const MOCK_ADS: Ad[] = [
    { 
        id: 99,
        businessId: 2,
        title: "Test Video: A Walk in the City", 
        structuredDescription: {
            benefit: "Experience our city's vibe, one step at a time.",
            features: "High-quality vertical video. Smooth scrolling experience.",
            solution: "Perfect for showcasing dynamic content and engaging users."
        },
        city: "Den Haag",
        category: "category_professional_services",
        mediaUrls: ["https://assets.mixkit.co/videos/preview/mixkit-woman-walking-on-a-street-in-a-rainy-day-4028-large.mp4"],
        mediaType: 'video',
        coverImageUrl: 'https://i.imgur.com/KzQ3f2U.jpeg',
        tags: ["#test", "#scrolling", "#denhaag"],
        isSponsored: true,
        likeCount: 999,
        commentCount: 42,
        isLikedByCurrentUser: false,
    },
    { 
        id: 1, 
        businessId: 1, 
        title: "New collection at Fashion Store", 
        structuredDescription: {
            benefit: "Look stunning with our latest fashion arrivals.",
            features: "Made from premium, sustainable fabrics. Available in multiple colors.",
            solution: "Find the perfect outfit for any occasion, from casual to formal."
        },
        city: "Rotterdam",
        category: "category_fashion",
        mediaUrls: ["https://assets.mixkit.co/videos/preview/mixkit-woman-posing-for-a-photo-shoot-in-a-studio-34208-large.mp4"],
        mediaType: 'video',
        coverImageUrl: 'https://i.imgur.com/9E6qB8E.jpeg',
        tags: ["#mode", "#kleding", "#nieuw"],
        isSponsored: true,
        discountPercentage: 40,
        likeCount: 1256,
        commentCount: 42,
        isLikedByCurrentUser: false,
        startDate: '2024-06-01',
        endDate: '2024-06-30',
        callToAction: { text: "Shop Now", link: "https://fashionstore.nl/new" }
    },
    { 
        id: 2, 
        businessId: 2, 
        title: "Morning Boost at Coffee Corner", 
        structuredDescription: {
            benefit: "Start your day with the best coffee in town.",
            features: "Locally roasted beans, expert baristas, cozy atmosphere.",
            solution: "Your daily caffeine fix and a perfect spot to relax or work."
        },
        city: "Den Haag",
        category: "category_food_drink",
        mediaUrls: ["https://assets.mixkit.co/videos/preview/mixkit-coffee-maker-making-a-shot-of-coffee-34220-large.mp4"],
        mediaType: 'video',
        coverImageUrl: 'https://i.imgur.com/O2jOC2c.jpeg',
        tags: ["#koffie", "#denhaag", "#ontbijt"],
        isSponsored: false,
        discountPercentage: 20,
        likeCount: 893,
        commentCount: 12,
        isLikedByCurrentUser: true,
    },
    { 
        id: 3, 
        businessId: 3, 
        title: "Authentic Italian Pizza", 
        structuredDescription: {
            benefit: "Taste a slice of Italy, delivered to your door.",
            features: "Wood-fired oven, fresh ingredients, traditional recipes.",
            solution: "The perfect dinner for a night in with family or friends."
        },
        city: "Amsterdam",
        category: "category_horeca",
        mediaUrls: ["https://assets.mixkit.co/videos/preview/mixkit-hot-and-delicious-pizza-on-a-wooden-board-4340-large.mp4"],
        mediaType: 'video',
        coverImageUrl: 'https://i.imgur.com/Uu8S02j.jpeg',
        tags: ["#pizza", "#amsterdam", "#italiaans"],
        isSponsored: false,
        likeCount: 2100,
        commentCount: 88,
        isLikedByCurrentUser: false,
        callToAction: { text: "Order Online", link: "https://mariospizza.nl/order" }
    },
];

export const MOCK_PROPERTY_LISTINGS: PropertyListing[] = [
  {
    id: 101,
    businessId: 5,
    title: "Charming Canal-View Apartment in City Center",
    address: { street: "Prinsengracht 25", postalCode: "1015 DK", city: "Amsterdam", country: "Netherlands" },
    status: PropertyStatus.ForRent,
    type: PropertyType.Apartment,
    price: 2500, // Per month for rent
    livingArea: 85,
    bedrooms: 2,
    bathrooms: 1,
    yearBuilt: 1920,
    energyLabel: "C",
    description: "Beautifully renovated apartment with stunning canal views. Features a modern kitchen, spacious living room, and authentic details. Located in the heart of the Jordaan, close to shops, restaurants, and public transport.",
    photos: [
      "https://i.imgur.com/tLq1Y5L.jpeg",
      "https://i.imgur.com/oV39k72.jpeg",
      "https://i.imgur.com/6XyL9a4.jpeg",
      "https://i.imgur.com/Y3zJ9bY.jpeg",
    ],
  },
  {
    id: 102,
    businessId: 5,
    title: "Spacious Family Home with Garden in Statenkwartier",
    address: { street: "Frederik Hendriklaan 180", postalCode: "2582 BK", city: "Den Haag", country: "Netherlands" },
    status: PropertyStatus.ForSale,
    type: PropertyType.House,
    price: 875000,
    livingArea: 160,
    plotSize: 220,
    bedrooms: 4,
    bathrooms: 2,
    yearBuilt: 1915,
    energyLabel: "D",
    description: "A wonderful family house in the highly sought-after Statenkwartier. This property boasts a large living area, four bedrooms, and a sunny southwest-facing garden. Close to international schools, the beach, and shopping streets.",
    photos: [
      "https://i.imgur.com/R2eYSAQ.jpeg",
      "https://i.imgur.com/Uv1t8yf.jpeg",
      "https://i.imgur.com/8FkSgN9.jpeg",
    ],
  },
  {
    id: 103,
    businessId: 5,
    title: "Modern Loft with Rooftop Terrace",
    address: { street: "Karel Doormanstraat 330", postalCode: "3012 GP", city: "Rotterdam", country: "Netherlands" },
    status: PropertyStatus.ForSale,
    type: PropertyType.Apartment,
    price: 650000,
    livingArea: 110,
    bedrooms: 2,
    bathrooms: 2,
    yearBuilt: 2018,
    energyLabel: "A",
    description: "Experience modern city living in this stunning loft apartment. With an open-plan design, high ceilings, and a private rooftop terrace, this property is perfect for those who love contemporary style. Located in the bustling city center of Rotterdam.",
    photos: [
      "https://i.imgur.com/IpH2v3L.jpeg",
      "https://i.imgur.com/0o3h8rO.jpeg",
    ],
  },
  {
    id: 104,
    businessId: 5,
    title: "Luxe Nieuwbouw Villa in De Plantage",
    address: { street: "Blanckestyn 2", postalCode: "4784 CA", city: "Moerdijk", country: "Netherlands" },
    status: PropertyStatus.ForSale,
    type: PropertyType.House,
    price: 1680000,
    priceType: 'kk',
    pricePerSqm: 4870,
    availabilityStatus: "Beschikbaar",
    offeredSince: "In overleg",
    livingArea: 386,
    plotSize: 880,
    volume: 1360,
    otherIndoorSpace: 16,
    buildingBoundOutdoorSpace: 92,
    totalRooms: 8,
    bedrooms: 6,
    bathrooms: 3,
    numberOfFloors: 3,
    bathroomFacilities: ["Dubbele wastafel", "Inloopdouche", "Toilet", "Douche", "Ligbad", "Wastafel"],
    amenities: ["Dakterras", "Zonnepanelen"],
    yearBuilt: 2024,
    constructionType: "Nieuwbouw",
    roofType: "Zadeldak bedekt met pannen",
    energyLabel: "A+++",
    insulation: ["Gedeeltelijk dubbel glas", "Muurisolatie", "Vloerisolatie", "Volledig geïsoleerd"],
    heating: ["Vloerverwarming geheel", "Warmte terugwininstallatie", "Warmtepomp"],
    certifications: ["Woningborg Garantiecertificaat"],
    description: "Nieuwbouw representatief in het hart van de Nieuwe Baan is een oase voor wie minimalistische woning maar allenklopt. Waar ruimte heeft te verhuizen, niet hoeft te aannemen, maar alleen nog maar hoeft te wonen. Aan de groene rand van woonwijk De Plantage in Midden ligt deze glasheldere villa van 386 vierkante meter gebouwd voor wie rust, ruimte en kwaliteit zoekt. De moderne architectuur, de doordachte indeling, de fijne tuin op het zuiden, alles ademt comfort. Extra corresponderen buiten het daglicht naar binnen: de verbinding die overal in het huis tot leven. Terwijl...",
    photos: [
      "https://i.imgur.com/zW1r5pX.jpeg",
      "https://i.imgur.com/R2eYSAQ.jpeg",
      "https://i.imgur.com/Uv1t8yf.jpeg",
      "https://i.imgur.com/tLq1Y5L.jpeg",
    ],
  }
];


export const MOCK_GALLERY_IMAGES: { [key: number]: string[] } = {
    1: [
        "https://i.imgur.com/9E6qB8E.jpeg",
        "https://i.imgur.com/S8S9v27.jpeg",
        "https://i.imgur.com/4YwP5E8.jpg",
        "https://i.imgur.com/jXqQp6j.jpeg",
        "https://i.imgur.com/3flwzJm.png",
    ],
    2: [
        "https://i.imgur.com/O2jOC2c.jpeg",
        "https://i.imgur.com/sC3bL2T.png",
        "https://i.imgur.com/zW1r5pX.jpeg",
    ],
    3: [
        "https://i.imgur.com/Uu8S02j.jpeg",
        "https://i.imgur.com/Yq2f0bJ.png",
        "https://i.imgur.com/8p8YJH8.png",
        "https://i.imgur.com/S8S9v27.jpeg",
    ],
    4: [
        "https://i.imgur.com/zW1r5pX.jpeg",
        "https://i.imgur.com/3flwzJm.png",
    ],
    5: [
        "https://i.imgur.com/Y3zJ9bY.jpeg",
        "https://i.imgur.com/R2eYSAQ.jpeg",
        "https://i.imgur.com/Uv1t8yf.jpeg",
        "https://i.imgur.com/tLq1Y5L.jpeg",
    ]
};

export const MOCK_COMMENTS: Comment[] = [
    { id: 1, adId: 1, postId: 0, author: "Sophie L.", avatarUrl: "https://i.imgur.com/9E6qB8E.jpeg", text: "Love the new collection! 😍 Already ordered the blue dress.", date: "2024-05-20T10:30:00Z" },
    { id: 2, adId: 1, postId: 0, author: "Mark D.", avatarUrl: "https://i.imgur.com/O2jOC2c.jpeg", text: "Great video quality. Looks professional.", date: "2024-05-20T11:00:00Z" },
    { id: 3, adId: 3, postId: 0, author: "Luigi M.", avatarUrl: "https://i.imgur.com/Yq2f0bJ.png", text: "Best pizza in town! 🍕", date: "2024-05-19T18:00:00Z" },
    { id: 4, adId: 3, postId: 0, author: "Anna V.", avatarUrl: "https://i.imgur.com/4YwP5E8.jpg", text: "Is delivery available to Amsterdam-Noord?", date: "2024-05-19T19:15:00Z" },
    { id: 5, adId: 3, postId: 0, author: "Mario's Pizzeria", avatarUrl: "https://i.imgur.com/Yq2f0bJ.png", text: "Hi Anna, yes we do! You can order via the link in our ad.", date: "2024-05-19T19:30:00Z" },
    { id: 6, adId: 0, postId: 1, author: "Mark D.", avatarUrl: "https://i.imgur.com/O2jOC2c.jpeg", text: "Looks amazing! ☕️", date: "2024-06-03T09:05:00Z" },
    { id: 7, adId: 0, postId: 2, author: "Anna V.", avatarUrl: "https://i.imgur.com/4YwP5E8.jpg", text: "Love this style! When is it available in-store?", date: "2024-06-02T13:00:00Z" },
];

export const MOCK_LIVE_CHAT_MESSAGES: LiveChatMessage[] = [
    { type: 'user', author: 'Sophie', avatar: 'https://i.imgur.com/9E6qB8E.jpeg', message: "Love this jacket! What sizes are available?" },
    { type: 'user', author: 'Mark', avatar: 'https://i.imgur.com/O2jOC2c.jpeg', message: "Is the material real leather?" },
    { type: 'host', author: 'Fashion Store', avatar: 'https://i.imgur.com/8p8YJH8.png', message: "Hi Sophie! It's available in S, M, L, and XL. Mark, yes it's 100% genuine leather!" },
    { type: 'user', author: 'Anna', avatar: 'https://i.imgur.com/4YwP5E8.jpg', message: "This is exactly what I was looking for! 🔥" },
    { type: 'system', message: "Host pinned a product: Denim Jacket" },
    { type: 'user', author: 'Ben T.', avatar: 'https://i.imgur.com/sC3bL2T.png', message: "Do you ship internationally?" },
    { type: 'host', author: 'Fashion Store', avatar: 'https://i.imgur.com/8p8YJH8.png', message: "Hi Ben, we currently only ship within the Netherlands." },
    { type: 'user', author: 'Luigi', avatar: 'https://i.imgur.com/Yq2f0bJ.png', message: "Can you show the back of the jacket?" },
];

export const MOCK_POSTS: Post[] = [
    {
        id: 1,
        businessId: 2, // Coffee Corner
        type: PostType.Photo,
        content: "Start your week right with our new single-origin roast from Ethiopia! ☕️ It has notes of blueberry and jasmine. #coffee #specialtycoffee #denhaag",
        mediaUrl: "https://i.imgur.com/O2jOC2c.jpeg",
        createdAt: "2024-06-03T09:00:00Z",
        likeCount: 124,
        commentCount: 12,
        isLikedByCurrentUser: false,
    },
    {
        id: 2,
        businessId: 1, // Fashion Store
        type: PostType.Video,
        content: "Our new summer collection just dropped! ☀️ Come find your perfect outfit. #fashion #summerstyle #rotterdam",
        mediaUrl: "https://assets.mixkit.co/videos/preview/mixkit-woman-posing-for-a-photo-shoot-in-a-studio-34208-large.mp4",
        createdAt: "2024-06-02T12:30:00Z",
        likeCount: 543,
        commentCount: 45,
        isLikedByCurrentUser: true,
    },
    {
        id: 3,
        businessId: 3, // Mario's Pizzeria
        type: PostType.Text,
        content: "Special offer this Tuesday: any two large pizzas for only €25! Dine-in or takeaway. 🍕🍕",
        createdAt: "2024-06-01T17:00:00Z",
        likeCount: 88,
        commentCount: 21,
        isLikedByCurrentUser: false,
    },
    {
        id: 4,
        businessId: 4, // Bloemen Paradise
        type: PostType.Photo,
        content: "Fresh peonies have arrived! Perfect for brightening up your home. 💐",
        mediaUrl: "https://i.imgur.com/zW1r5pX.jpeg",
        createdAt: "2024-05-31T11:00:00Z",
        likeCount: 210,
        commentCount: 15,
        isLikedByCurrentUser: true,
    },
];